//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SHLife.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SHLife.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Logo {
            get {
                object obj = ResourceManager.GetObject("Logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 兼职
        ///招聘
        ///网络
        ///QQ
        ///招聘
        ///有意者
        ///到货
        ///本店
        ///代购
        ///扣扣
        ///客服
        ///微店
        ///兼职
        ///兼值
        ///淘宝
        ///小姐
        ///妓女
        ///包夜
        ///3P
        ///LY
        ///JS
        ///狼友
        ///技师
        ///推油
        ///胸推
        ///BT
        ///毒龙
        ///口爆
        ///兼职
        ///楼凤
        ///足交
        ///口暴
        ///口交
        ///全套
        ///SM
        ///桑拿
        ///吞精
        ///咪咪
        ///婊子
        ///乳方
        ///操逼
        ///全职
        ///性伴侣
        ///网购
        ///网络工作
        ///代理
        ///专业代理
        ///帮忙点一下
        ///帮忙点下
        ///请点击进入
        ///详情请进入
        ///私人侦探
        ///私家侦探
        ///针孔摄象
        ///调查婚外情
        ///信用卡提现
        ///无抵押贷款
        ///广告代理
        ///原音铃声
        ///借腹生子
        ///找个妈妈
        ///找个爸爸
        ///代孕妈妈
        ///代生孩子
        ///代开发票
        ///腾讯客服电话
        ///销售热线
        ///免费订购热线
        ///低价出售
        ///款到发货
        ///回复可见
        ///连锁加盟
        ///加盟连锁
        ///免费二级域名
        ///免费使用
        ///免费索取
        ///蚁力神
        ///婴儿汤
        ///售肾
        ///刻章办
        ///买小车
        ///套牌车
        ///玛雅网
        ///电脑传讯
        ///视频来源
        ///下载速度
        ///高清在线
        ///全集在线
        ///在线播放
        ///txt下载
        ///六位qq
        ///6位qq
        ///位的qq
        ///个qb
        ///送qb
        ///用刀横向切腹
        ///完全自杀手册
        ///四海帮
        ///足球投注
        ///地下钱庄
        ///中国复兴党
        ///阿波罗网
        ///曾道人
        ///六合彩
        ///改卷内幕
        ///替考试
        ///隐形耳机
        ///出售答案
        ///考中答案
        ///答an
        ///da案
        ///资金周转
        ///救市
        ///股市圈钱
        ///崩盘
        ///资金短缺
        ///证监会
        ///质押贷款
        ///小额贷款
        ///周小川
        ///刘明康
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string 广告 {
            get {
                return ResourceManager.GetString("广告", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 习近平
        ///平近习
        ///xjp
        ///习太子
        ///习明泽
        ///老习
        ///温家宝
        ///温加宝
        ///温x
        ///温jia宝
        ///温宝宝
        ///温加饱
        ///温加保
        ///张培莉
        ///温云松
        ///温如春
        ///温jb
        ///胡温
        ///胡x
        ///胡jt
        ///胡boss
        ///胡总
        ///胡王八
        ///hujintao
        ///胡jintao
        ///胡j涛
        ///胡惊涛
        ///胡景涛
        ///胡紧掏
        ///湖紧掏
        ///胡紧套
        ///锦涛
        ///hjt
        ///胡派
        ///胡主席
        ///刘永清
        ///胡海峰
        ///胡海清
        ///江泽民
        ///民泽江
        ///江胡
        ///江哥
        ///江主席
        ///江书记
        ///江浙闽
        ///江沢民
        ///江浙民
        ///择民
        ///则民
        ///茳泽民
        ///zemin
        ///ze民
        ///老江
        ///老j
        ///江core
        ///江x
        ///江派
        ///江zm
        ///jzm
        ///江戏子
        ///江蛤蟆
        ///江某某
        ///江贼
        ///江猪
        ///江氏集团
        ///江绵恒
        ///江绵康
        ///王冶坪
        ///江泽慧
        ///邓小平
        ///平小邓
        ///xiao平
        ///邓xp
        ///邓晓平
        ///邓朴方
        ///邓榕
        ///邓质方
        ///毛泽东
        ///猫泽东
        ///猫则东
        ///猫贼洞
        ///毛zd
        ///毛zx
        ///z东
        ///ze东
        ///泽d
        ///zedong
        ///毛太祖
        ///毛相
        ///主席画像
        ///改革历程
        ///朱镕基
        ///朱容基
        ///朱镕鸡
        ///朱容鸡
        ///朱云来
        ///李鹏
        ///李peng
        ///里鹏
        ///李月月鸟
        ///李小鹏
        ///李小琳
        ///华主席
        ///华国
        ///国锋
        ///国峰
        ///锋同志
        ///白春礼
        ///薄熙来
        ///薄一波
        ///蔡赴朝
        ///蔡武
        ///曹刚川
        ///常万全
        ///陈炳德
        ///陈德铭
        ///陈建国
        ///陈良宇
        ///陈绍基
        ///陈同海
        ///陈至立
        ///戴秉国
        ///丁一平
        ///董建华
        ///杜德印
        ///杜世成
        ///傅锐
        ///郭伯雄
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string 政治类 {
            get {
                return ResourceManager.GetString("政治类", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 出售雷管
        ///炸药
        ///炸药
        ///出售炸药
        ///出售炸药 电话
        ///制作火药配方
        ///炸药出售 
        ///出售雷管炸药
        ///火药配方
        ///在家里做原子弹
        ///硝酸甘油炸弹制作
        ///TNT 炸弹的制作
        ///硝铵炸药配方
        ///硝酸甘油制作
        ///炸弹配方
        ///简易炸药
        ///火药制作简易炸弹
        ///炸弹制作
        ///硝酸甘油
        ///硝酸甘油炸弹制作方法
        ///手把手教你做炸弹
        ///恐怖分子傻瓜手册
        ///氢弹手工制作方法
        ///起爆器
        ///自制燃烧弹
        ///燃烧弹
        ///弹药制造方法
        ///液体炸药配方
        ///炸药配方与制作
        ///自制炸药配方
        ///tnt炸药成分
        ///炸药的制作
        ///tnt炸药配方
        ///各种炸药配方大全
        ///炸药的成分
        ///燃烧弹的制作方 
        ///黑火药的配方
        ///黑火药的制作
        ///黑火药比例
        ///燃烧弹 制作
        ///黑火药配方比例
        ///黑火药的成分
        ///原子弹配方
        ///原子弹DIY教程
        ///C4炸药
        ///雷管出售
        ///制作硝化甘油
        ///DIY核弹
        ///核弹制作方法
        ///原子弹制作手册
        ///简易原子弹教程
        ///黑火药配方
        ///自制炸药方法
        ///教你怎么用土办法做武器
        ///莫洛托夫鸡尾酒的配方
        ///zz炸弹的制作方法
        ///C4炸药的成分
        ///炸药制造生产工艺
        ///原子弹制造完全手册
        ///「红烧兔子」大餐
        ///汽车炸弹制作
        ///人体炸弹制作流程
        ///炸弹制 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string 涉枪涉爆 {
            get {
                return ResourceManager.GetString("涉枪涉爆", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 000.2011wyt.com
        ///000.bbexe.cn
        ///0000-qq.cn
        ///00000-qq.cn
        ///0008-qq.cn
        ///000wyt.com
        ///001.bbexe.cn
        ///001fans.com
        ///002.la
        ///00333.cn
        ///005.70o2.cn
        ///006001.com
        ///0073d.cn
        ///007wyt.com
        ///008.kweilai.cn
        ///008.qq8625.cn
        ///008.renyi1.cn
        ///008.wangwang1.cn
        ///008.youyiv.cn
        ///008.zhifong.cn
        ///00852555.cn
        ///00852tm888.com
        ///008567.cn
        ///00ad.3322.org
        ///00ooll.cn
        ///00pp00.360yyy.8800.org
        ///00zzd.2288.org
        ///010246.com
        ///010268.com
        ///010389.com
        ///010488.com
        ///0105568.cn
        ///01058789.com
        ///0106658.cn
        ///0106677.cn
        ///0108686.cn
        ///0108818.cn
        ///010899.com
        ///01090 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string 网址 {
            get {
                return ResourceManager.GetString("网址", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 爱液,
        ///按摩棒,
        ///拔出来,
        ///爆草,
        ///包二奶,
        ///暴干,
        ///暴奸,
        ///暴乳,
        ///爆乳,
        ///暴淫,
        ///被操,
        ///被插,
        ///被干,
        ///逼奸,
        ///仓井空,
        ///插暴,
        ///操逼,
        ///操黑,
        ///操烂,
        ///肏你,
        ///肏死,
        ///操死,
        ///操我,
        ///厕奴,
        ///插比,
        ///插b,
        ///插逼,
        ///插进,
        ///插你,
        ///插我,
        ///插阴,
        ///潮吹,
        ///潮喷,
        ///成人电影,
        ///成人论坛,
        ///成人色情,
        ///成人网站,
        ///成人文学,
        ///成人小说,
        ///艳情小说,
        ///成人游戏,
        ///吃精,
        ///抽插,
        ///春药,
        ///大波,
        ///大力抽送,
        ///大乳,
        ///荡妇,
        ///荡女,
        ///盗撮,
        ///发浪,
        ///放尿,
        ///肥逼,
        ///粉穴,
        ///风月大陆,
        ///干死你,
        ///干穴,
        ///肛交,
        ///肛门,
        ///龟头,
        ///裹本,
        ///国产av,
        ///好嫩,
        ///豪乳,
        ///黑逼,
        ///后庭,
        ///后穴,
        ///虎骑,
        ///换妻俱乐部,
        ///黄片,
        ///几吧,
        ///鸡吧,
        ///鸡巴,
        ///鸡奸,
        ///妓女,
        ///奸情,
        ///叫床,
        ///脚交,
        ///精液,
        ///就去日,
        ///巨屌,
        ///菊花洞,
        ///菊门,
        ///巨奶,
        ///巨乳,
        ///菊穴,
        ///开苞,
        ///口爆,
        ///口活,
        ///口交,
        ///口射,
        ///口淫,
        ///裤袜,
        ///狂操,
        ///狂插,
        ///浪逼,
        ///浪妇,
        ///浪叫,
        ///浪女,
        ///狼友,
        ///聊性,
        ///凌辱,
        ///漏乳,
        ///露b,
        ///乱交,
        ///乱伦,
        ///轮暴,
        ///轮操,
        ///轮奸,
        ///裸陪,
        ///买春,
        ///美逼,
        ///美少妇,
        ///美乳,
        ///美腿,
        ///美穴,
        ///美幼,
        ///秘唇,
        ///迷奸,
        ///密穴, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string 色情类 {
            get {
                return ResourceManager.GetString("色情类", resourceCulture);
            }
        }
    }
}
