//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FastestSHLife
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChatRoomMember
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ChatRoomMember()
        {
            this.ChatRoomRecord = new HashSet<ChatRoomRecord>();
        }
    
        public System.Guid ChatRoomMemberId { get; set; }
        public long ChatRoomMemberNo { get; set; }
        public System.Guid ChatRoomId { get; set; }
        public System.Guid AccountId { get; set; }
        public int Role { get; set; }
        public System.DateTimeOffset CreateDateTime { get; set; }
        public Nullable<System.DateTimeOffset> UpdateDateTime { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual ChatRoom ChatRoom { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChatRoomRecord> ChatRoomRecord { get; set; }
    }
}
