//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FastestSHLife
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class a : DbContext
    {
        public a()
            : base("name=a")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Account { get; set; }
        public virtual DbSet<ChatReviewTask> ChatReviewTask { get; set; }
        public virtual DbSet<ChatRoom> ChatRoom { get; set; }
        public virtual DbSet<ChatRoomMember> ChatRoomMember { get; set; }
        public virtual DbSet<ChatRoomRecord> ChatRoomRecord { get; set; }
        public virtual DbSet<Friend> Friend { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
