//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SHLife
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChatRoomMember
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ChatRoomMember()
        {
            this.ChatRoomRecords = new HashSet<ChatRoomRecord>();
        }
    
        public System.Guid ChatRoomMemberId { get; set; }
        public long ChatRoomMemberNo { get; set; }
        public System.Guid ChatRoomId { get; set; }
        public System.Guid AccountId { get; set; }
        public int Role { get; set; }
        public System.DateTimeOffset CreateDateTime { get; set; }
        public Nullable<System.DateTimeOffset> UpdateDateTime { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual ChatRoom ChatRoom { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChatRoomRecord> ChatRoomRecords { get; set; }
    }
}
