//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SHLife
{
    using System;
    using System.Collections.Generic;
    
    public partial class New_ChatReviewTask
    {
        public System.Guid New_ReviewId { get; set; }
        public System.Guid New_ChatRoomRecordId { get; set; }
        public string New_DetectedKeyword { get; set; }
        public byte New_ReviewStatus { get; set; }
        public System.DateTimeOffset New_CreateDateTime { get; set; }
    
        public virtual ChatRoomRecord ChatRoomRecord { get; set; }
    }
}
