//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SHLife
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChatRoomRecord
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ChatRoomRecord()
        {
            this.ChatReviewTasks = new HashSet<ChatReviewTask>();
        }
    
        public System.Guid ChatRoomRecordId { get; set; }
        public long ChatRoomRecordNo { get; set; }
        public System.Guid ChatRoomId { get; set; }
        public Nullable<System.Guid> ChatRoomMemberId { get; set; }
        public string Message { get; set; }
        public System.DateTimeOffset CreateDateTime { get; set; }
        public Nullable<System.DateTimeOffset> UpdateDateTime { get; set; }
    
        public virtual ChatRoom ChatRoom { get; set; }
        public virtual ChatRoomMember ChatRoomMember { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChatReviewTask> ChatReviewTasks { get; set; }
    }
}
