//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SHLife
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChatReviewTask
    {
        public System.Guid ReviewId { get; set; }
        public System.Guid ChatRoomRecordId { get; set; }
        public string DetectedKeyword { get; set; }
        public byte ReviewStatus { get; set; }
        public System.DateTimeOffset CreateDateTime { get; set; }
        public string New_KeywordType { get; set; }
    
        public virtual ChatRoomRecord ChatRoomRecord { get; set; }
    }
}
